### ISSUE TITLE
'setacl' is not recognized 

### ISSUE THREAD

**Issue by enseitankado** [dheerajbhaskar/pleasant-windows#1]
'setacl' is not recognized as an internal or external command, operable program or batch file.

**Comment by dheerajbhaskar** [comment]
@enseitankado please give the following details:

1. Your windows version
2. Steps to reproduce your error (a screen video recording will be helpful)

**Comment by dheerajbhaskar** [comment]
Please reply when this issue reoccurs, closing due to no response
